<a href="https://colab.research.google.com/github/Rohith616/Client-Project-1/blob/main/EvalML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install evalml

Collecting evalml
  Downloading evalml-0.43.0-py3-none-any.whl (6.4 MB)
     |████████████████████████████████| 6.4 MB 4.9 MB/s
Collecting texttable>=1.6.2
  Downloading texttable-1.6.4-py2.py3-none-any.whl (10 kB)
Collecting requirements-parser>=0.2.0
  Downloading requirements_parser-0.5.0-py3-none-any.whl (18 kB)
Collecting matplotlib>=3.3.3
  Downloading matplotlib-3.5.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (11.2 MB)
     |████████████████████████████████| 11.2 MB 53.4 MB/s
Requirement already satisfied: scikit-learn>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from evalml) (1.0.2)
Collecting scipy>=1.5.0
  Downloading scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)
     |████████████████████████████████| 38.1 MB 54.3 MB/s
Collecting pmdarima>=1.8.1
  Downloading pmdarima-1.8.5-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 38.4 MB/s
Collecting colorama>=0.4.4
  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting lime>=0.2.0.1
  Downloading lime-0.2.0.1.tar.gz (275 kB)
     |████████████████████████████████| 275 kB 46.0 MB/s
Requirement already satisfied: pyzmq>=20.0.0 in /usr/local/lib/python3.7/dist-packages (from evalml) (22.3.0)
Collecting kaleido>=0.1.0
  Downloading kaleido-0.2.1-py2.py3-none-manylinux1_x86_64.whl (79.9 MB)
     |████████████████████████████████| 79.9 MB 154 kB/s
Collecting vowpalwabbit>=8.11.0
  Downloading vowpalwabbit-9.0.1-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (3.0 MB)
     |████████████████████████████████| 3.0 MB 29.9 MB/s
Collecting cloudpickle>=1.5.0
  Downloading cloudpickle-2.0.0-py3-none-any.whl (25 kB)
Requirement already satisfied: seaborn>=0.11.1 in /usr/local/lib/python3.7/dist-packages (from evalml) (0.11.2)
Requirement already satisfied: click>=7.1.2 in /usr/local/lib/python3.7/dist-packages (from evalml) (7.1.2)
Requirement already satisfied: ipywidgets>=7.5 in /usr/local/lib/python3.7/dist-packages (from evalml) (7.6.5)
Collecting catboost>=0.20
  Downloading catboost-1.0.4-cp37-none-manylinux1_x86_64.whl (76.1 MB)
     |████████████████████████████████| 76.1 MB 57 kB/s
Requirement already satisfied: plotly>=5.0.0 in /usr/local/lib/python3.7/dist-packages (from evalml) (5.5.0)
Collecting networkx<2.6,>=2.5
  Downloading networkx-2.5.1-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 56.5 MB/s
Collecting statsmodels>=0.12.2
  Downloading statsmodels-0.13.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.8 MB)
     |████████████████████████████████| 9.8 MB 42.8 MB/s
Collecting featuretools>=1.2.0
  Downloading featuretools-1.6.0-py3-none-any.whl (356 kB)
     |████████████████████████████████| 356 kB 41.0 MB/s
Collecting lightgbm>=2.3.1
  Downloading lightgbm-3.3.2-py3-none-manylinux1_x86_64.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 46.9 MB/s
Collecting graphviz>=0.13
  Downloading graphviz-0.19.1-py3-none-any.whl (46 kB)
     |████████████████████████████████| 46 kB 3.9 MB/s
Requirement already satisfied: imbalanced-learn>=0.8.0 in /usr/local/lib/python3.7/dist-packages (from evalml) (0.8.1)
Collecting scikit-optimize>=0.8.1
  Downloading scikit_optimize-0.9.0-py2.py3-none-any.whl (100 kB)
     |████████████████████████████████| 100 kB 9.1 MB/s
Requirement already satisfied: pandas<1.4.0,>=1.3.0 in /usr/local/lib/python3.7/dist-packages (from evalml) (1.3.5)
Collecting shap>=0.36.0
  Downloading shap-0.40.0-cp37-cp37m-manylinux2010_x86_64.whl (564 kB)
     |████████████████████████████████| 564 kB 52.8 MB/s
Collecting xgboost>=1.4.2
  Downloading xgboost-1.5.2-py3-none-manylinux2014_x86_64.whl (173.6 MB)
     |████████████████████████████████| 173.6 MB 6.6 kB/s
Collecting category-encoders>=2.2.2
  Downloading category_encoders-2.3.0-py2.py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 369 kB/s
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.7/dist-packages (from evalml) (1.21.5)
Collecting woodwork>=0.11.0
  Downloading woodwork-0.13.0-py3-none-any.whl (170 kB)
     |████████████████████████████████| 170 kB 60.3 MB/s
Collecting dask>=2021.10.0
  Downloading dask-2022.2.0-py3-none-any.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 43.5 MB/s
Collecting nlp-primitives>=2.1.0
  Downloading nlp_primitives-2.3.0-py3-none-any.whl (44.7 MB)
     |████████████████████████████████| 44.7 MB 1.5 MB/s
Collecting sktime>=0.7.0
  Downloading sktime-0.10.1-py3-none-any.whl (6.5 MB)
     |████████████████████████████████| 6.5 MB 24.0 MB/s
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from catboost>=0.20->evalml) (1.15.0)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.7/dist-packages (from category-encoders>=2.2.2->evalml) (0.5.2)
Collecting pyyaml>=5.3.1
  Downloading PyYAML-6.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (596 kB)
     |████████████████████████████████| 596 kB 56.0 MB/s
Requirement already satisfied: toolz>=0.8.2 in /usr/local/lib/python3.7/dist-packages (from dask>=2021.10.0->evalml) (0.11.2)
Collecting fsspec>=0.6.0
  Downloading fsspec-2022.2.0-py3-none-any.whl (134 kB)
     |████████████████████████████████| 134 kB 71.3 MB/s
Collecting partd>=0.3.10
  Downloading partd-1.2.0-py3-none-any.whl (19 kB)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from dask>=2021.10.0->evalml) (21.3)
Collecting distributed>=2021.10.0
  Downloading distributed-2022.2.0-py3-none-any.whl (837 kB)
     |████████████████████████████████| 837 kB 47.8 MB/s
Collecting psutil>=5.6.6
  Downloading psutil-5.9.0-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (280 kB)
     |████████████████████████████████| 280 kB 45.1 MB/s
Requirement already satisfied: tqdm>=4.32.0 in /usr/local/lib/python3.7/dist-packages (from featuretools>=1.2.0->evalml) (4.62.3)
Collecting holidays>=0.13
  Downloading holidays-0.13-py3-none-any.whl (172 kB)
     |████████████████████████████████| 172 kB 50.8 MB/s
Requirement already satisfied: zict>=0.1.3 in /usr/local/lib/python3.7/dist-packages (from distributed>=2021.10.0->featuretools>=1.2.0->evalml) (2.0.0)
Requirement already satisfied: tornado>=5 in /usr/local/lib/python3.7/dist-packages (from distributed>=2021.10.0->featuretools>=1.2.0->evalml) (5.1.1)
Requirement already satisfied: sortedcontainers!=2.0.0,!=2.0.1 in /usr/local/lib/python3.7/dist-packages (from distributed>=2021.10.0->featuretools>=1.2.0->evalml) (2.4.0)
Requirement already satisfied: tblib>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from distributed>=2021.10.0->featuretools>=1.2.0->evalml) (1.7.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from distributed>=2021.10.0->featuretools>=1.2.0->evalml) (2.11.3)
Requirement already satisfied: msgpack>=0.6.0 in /usr/local/lib/python3.7/dist-packages (from distributed>=2021.10.0->featuretools>=1.2.0->evalml) (1.0.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from distributed>=2021.10.0->featuretools>=1.2.0->evalml) (57.4.0)
Requirement already satisfied: korean-lunar-calendar in /usr/local/lib/python3.7/dist-packages (from holidays>=0.13->featuretools>=1.2.0->evalml) (0.2.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from holidays>=0.13->featuretools>=1.2.0->evalml) (2.8.2)
Requirement already satisfied: hijri-converter in /usr/local/lib/python3.7/dist-packages (from holidays>=0.13->featuretools>=1.2.0->evalml) (2.2.3)
Requirement already satisfied: convertdate>=2.3.0 in /usr/local/lib/python3.7/dist-packages (from holidays>=0.13->featuretools>=1.2.0->evalml) (2.4.0)
Requirement already satisfied: pymeeus<=1,>=0.3.13 in /usr/local/lib/python3.7/dist-packages (from convertdate>=2.3.0->holidays>=0.13->featuretools>=1.2.0->evalml) (0.5.11)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from imbalanced-learn>=0.8.0->evalml) (1.1.0)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.5->evalml) (0.2.0)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.5->evalml) (4.10.1)
Requirement already satisfied: nbformat>=4.2.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.5->evalml) (5.1.3)
Requirement already satisfied: ipython>=4.0.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.5->evalml) (5.5.0)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.5->evalml) (1.0.2)
Requirement already satisfied: traitlets>=4.3.1 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.5->evalml) (5.1.1)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.5->evalml) (3.5.2)
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.7/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.5->evalml) (5.3.5)
Requirement already satisfied: pexpect in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0->ipywidgets>=7.5->evalml) (4.8.0)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0->ipywidgets>=7.5->evalml) (1.0.18)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0->ipywidgets>=7.5->evalml) (4.4.2)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0->ipywidgets>=7.5->evalml) (2.6.1)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0->ipywidgets>=7.5->evalml) (0.7.5)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python3.7/dist-packages (from ipython>=4.0.0->ipywidgets>=7.5->evalml) (0.8.1)
Requirement already satisfied: wheel in /usr/local/lib/python3.7/dist-packages (from lightgbm>=2.3.1->evalml) (0.37.1)
Requirement already satisfied: scikit-image>=0.12 in /usr/local/lib/python3.7/dist-packages (from lime>=0.2.0.1->evalml) (0.18.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.3.3->evalml) (1.3.2)
Collecting fonttools>=4.22.0
  Downloading fonttools-4.29.1-py3-none-any.whl (895 kB)
     |████████████████████████████████| 895 kB 38.8 MB/s
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.3.3->evalml) (7.1.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.3.3->evalml) (0.11.0)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.3.3->evalml) (3.0.7)
Requirement already satisfied: jupyter-core in /usr/local/lib/python3.7/dist-packages (from nbformat>=4.2.0->ipywidgets>=7.5->evalml) (4.9.2)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /usr/local/lib/python3.7/dist-packages (from nbformat>=4.2.0->ipywidgets>=7.5->evalml) (4.3.3)
Requirement already satisfied: importlib-resources>=1.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.5->evalml) (5.4.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.5->evalml) (0.18.1)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.5->evalml) (21.4.0)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.5->evalml) (4.11.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.5->evalml) (3.10.0.2)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.7/dist-packages (from importlib-resources>=1.4.0->jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.5->evalml) (3.7.0)
Collecting nltk>=3.4.5
  Downloading nltk-3.7-py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 38.0 MB/s
Collecting regex>=2021.8.3
  Downloading regex-2022.3.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (749 kB)
     |████████████████████████████████| 749 kB 54.1 MB/s
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas<1.4.0,>=1.3.0->evalml) (2018.9)
Collecting locket
  Downloading locket-0.2.1-py2.py3-none-any.whl (4.1 kB)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from plotly>=5.0.0->evalml) (8.0.1)
Requirement already satisfied: Cython!=0.29.18,>=0.29 in /usr/local/lib/python3.7/dist-packages (from pmdarima>=1.8.1->evalml) (0.29.28)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/dist-packages (from pmdarima>=1.8.1->evalml) (1.24.3)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=4.0.0->ipywidgets>=7.5->evalml) (0.2.5)
Collecting types-setuptools>=57.0.0
  Downloading types_setuptools-57.4.9-py3-none-any.whl (27 kB)
Requirement already satisfied: tifffile>=2019.7.26 in /usr/local/lib/python3.7/dist-packages (from scikit-image>=0.12->lime>=0.2.0.1->evalml) (2021.11.2)
Requirement already satisfied: imageio>=2.3.0 in /usr/local/lib/python3.7/dist-packages (from scikit-image>=0.12->lime>=0.2.0.1->evalml) (2.4.1)
Requirement already satisfied: PyWavelets>=1.1.1 in /usr/local/lib/python3.7/dist-packages (from scikit-image>=0.12->lime>=0.2.0.1->evalml) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.24.0->evalml) (3.1.0)
Collecting pyaml>=16.9
  Downloading pyaml-21.10.1-py2.py3-none-any.whl (24 kB)
Collecting slicer==0.0.7
  Downloading slicer-0.0.7-py3-none-any.whl (14 kB)
Requirement already satisfied: numba in /usr/local/lib/python3.7/dist-packages (from shap>=0.36.0->evalml) (0.51.2)
Collecting numba
  Downloading numba-0.55.1-1-cp37-cp37m-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 53.1 MB/s
Collecting deprecated>=1.2.13
  Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.7/dist-packages (from deprecated>=1.2.13->sktime>=0.7.0->evalml) (1.13.3)
Collecting llvmlite<0.39,>=0.38.0rc1
  Downloading llvmlite-0.38.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.5 MB)
     |████████████████████████████████| 34.5 MB 16 kB/s
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.7/dist-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (5.3.1)
Requirement already satisfied: Send2Trash in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (1.8.0)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (5.6.1)
Requirement already satisfied: terminado>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (0.13.1)
Requirement already satisfied: ptyprocess in /usr/local/lib/python3.7/dist-packages (from terminado>=0.8.1->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (0.7.0)
Requirement already satisfied: heapdict in /usr/local/lib/python3.7/dist-packages (from zict>=0.1.3->distributed>=2021.10.0->featuretools>=1.2.0->evalml) (1.0.1)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->distributed>=2021.10.0->featuretools>=1.2.0->evalml) (2.0.1)
Requirement already satisfied: bleach in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (4.1.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (0.7.1)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (0.8.4)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (0.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (1.5.0)
Requirement already satisfied: testpath in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (0.6.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.7/dist-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.5->evalml) (0.5.1)
Building wheels for collected packages: lime
  Building wheel for lime (setup.py) ... done
  Created wheel for lime: filename=lime-0.2.0.1-py3-none-any.whl size=283857 sha256=f880f0718f42a165da83151564122ece92e4dbad7d2d8d75fbfb0b18a9255ce2
  Stored in directory: /root/.cache/pip/wheels/ca/cb/e5/ac701e12d365a08917bf4c6171c0961bc880a8181359c66aa7
Successfully built lime
Installing collected packages: locket, scipy, pyyaml, partd, fsspec, cloudpickle, psutil, fonttools, dask, woodwork, regex, networkx, matplotlib, llvmlite, holidays, distributed, types-setuptools, statsmodels, slicer, pyaml, numba, nltk, graphviz, featuretools, deprecated, xgboost, vowpalwabbit, texttable, sktime, shap, scikit-optimize, requirements-parser, pmdarima, nlp-primitives, lime, lightgbm, kaleido, colorama, category-encoders, catboost, evalml
  Attempting uninstall: scipy
    Found existing installation: scipy 1.4.1
    Uninstalling scipy-1.4.1:
      Successfully uninstalled scipy-1.4.1
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
  Attempting uninstall: cloudpickle
    Found existing installation: cloudpickle 1.3.0
    Uninstalling cloudpickle-1.3.0:
      Successfully uninstalled cloudpickle-1.3.0
  Attempting uninstall: psutil
    Found existing installation: psutil 5.4.8
    Uninstalling psutil-5.4.8:
      Successfully uninstalled psutil-5.4.8
  Attempting uninstall: dask
    Found existing installation: dask 2.12.0
    Uninstalling dask-2.12.0:
      Successfully uninstalled dask-2.12.0
  Attempting uninstall: regex
    Found existing installation: regex 2019.12.20
    Uninstalling regex-2019.12.20:
      Successfully uninstalled regex-2019.12.20
  Attempting uninstall: networkx
    Found existing installation: networkx 2.6.3
    Uninstalling networkx-2.6.3:
      Successfully uninstalled networkx-2.6.3
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.2.2
    Uninstalling matplotlib-3.2.2:
      Successfully uninstalled matplotlib-3.2.2
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.34.0
    Uninstalling llvmlite-0.34.0:
      Successfully uninstalled llvmlite-0.34.0
  Attempting uninstall: holidays
    Found existing installation: holidays 0.10.5.2
    Uninstalling holidays-0.10.5.2:
      Successfully uninstalled holidays-0.10.5.2
  Attempting uninstall: distributed
    Found existing installation: distributed 1.25.3

In [ ]:
import pandas as pd
data = pd.read_csv('/content/preprocessed_data.csv')

In [ ]:
data.tail()

      Unnamed: 0          ds  target_id  ... weather  temp_max temp_min
3501        1748  2019-10-15          1  ...   sunny      23.1     14.6
3502        1749  2019-10-16          1  ...   sunny      22.4     12.8
3503        1750  2019-10-17          1  ...   cloud      23.7     14.3
3504        1751  2019-10-18          1  ...   cloud      24.0     18.4
3505        1752  2019-10-19          1  ...   cloud      25.0     18.4

[5 rows x 13 columns]

In [ ]:
data['target_id'].unique()

array([0, 1])

In [ ]:

data['event'].fillna("no event", inplace = True)
data['holiday'].fillna("休日なし", inplace = True)

In [ ]:
data

      Unnamed: 0          ds  target_id  ... weather  temp_max temp_min
0              0  2015-01-01          0  ...   cloud       8.2      0.7
1              1  2015-01-02          0  ...   sunny       7.9     -2.2
2              2  2015-01-03          0  ...   sunny       8.9     -1.1
3              3  2015-01-04          0  ...   cloud       9.3     -0.4
4              4  2015-01-05          0  ...   sunny      12.9      1.3
...          ...         ...        ...  ...     ...       ...      ...
3501        1748  2019-10-15          1  ...   sunny      23.1     14.6
3502        1749  2019-10-16          1  ...   sunny      22.4     12.8
3503        1750  2019-10-17          1  ...   cloud      23.7     14.3
3504        1751  2019-10-18          1  ...   cloud      24.0     18.4
3505        1752  2019-10-19          1  ...   cloud      25.0     18.4

[3506 rows x 13 columns]

In [ ]:
from datetime import datetime
data['ds']=pd.to_datetime(data['ds'] )

In [ ]:
data

      Unnamed: 0         ds  target_id  ... weather  temp_max temp_min
0              0 2015-01-01          0  ...   cloud       8.2      0.7
1              1 2015-01-02          0  ...   sunny       7.9     -2.2
2              2 2015-01-03          0  ...   sunny       8.9     -1.1
3              3 2015-01-04          0  ...   cloud       9.3     -0.4
4              4 2015-01-05          0  ...   sunny      12.9      1.3
...          ...        ...        ...  ...     ...       ...      ...
3501        1748 2019-10-15          1  ...   sunny      23.1     14.6
3502        1749 2019-10-16          1  ...   sunny      22.4     12.8
3503        1750 2019-10-17          1  ...   cloud      23.7     14.3
3504        1751 2019-10-18          1  ...   cloud      24.0     18.4
3505        1752 2019-10-19          1  ...   cloud      25.0     18.4

[3506 rows x 13 columns]

In [ ]:
data.isna().sum()

Unnamed: 0        0
ds                0
target_id         0
target_address    0
y                 0
event             0
cat_r             0
reg_wind          0
reg_r             0
holiday           0
weather           0
temp_max          0
temp_min          0
dtype: int64

In [ ]:
df =data.select_dtypes(include='object')
  
df=df.drop(['target_address'],axis=1)
for cols in df:
  dummies =pd.get_dummies(df[cols],drop_first=True)
  df = pd.concat([df,dummies],axis='columns')
data=pd.concat([data,df],axis='columns')
data=data.drop(['target_address','Unnamed: 0','event','cat_r','holiday','weather'],axis=1)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3506 entries, 0 to 3505
Data columns (total 33 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ds         3506 non-null   datetime64[ns]
 1   target_id  3506 non-null   int64
 2   y          3506 non-null   float64
 3   reg_wind   3506 non-null   float64
 4   reg_r      3506 non-null   float64
 5   temp_max   3506 non-null   float64
 6   temp_min   3506 non-null   float64
 7   event2     3506 non-null   uint8
 8   event3     3506 non-null   uint8
 9   no event   3506 non-null   uint8
 10  cat_r_1    3506 non-null   uint8
 11  みどりの日      3506 non-null   uint8
 12  休日なし       3506 non-null   uint8
 13  体育の日       3506 non-null   uint8
 14  元日         3506 non-null   uint8
 15  勤労感謝の日     3506 non-null   uint8
 16  国民の休日      3506 non-null   uint8
 17  天皇の即位の日    3506 non-null   uint8
 18  天皇誕生日      3506 non-null   uint8
 19  山の日        3506 non-null   uint8
 20  建国記念の日     3506 non-null   uint8
 21  憲法記念日      3506 non-null   uint8
 22  成人の日       3506 non-null   uint8
 23  振替休日       3506 non-null   uint8
 24  敬老の日       3506 non-null   uint8
 25  文化の日       3506 non-null   uint8
 26  春分の日       3506 non-null   uint8
 27  昭和の日       3506 non-null   uint8
 28  海の日        3506 non-null   uint8
 29  秋分の日       3506 non-null   uint8
 30  rain       3506 non-null   uint8
 31  snow       3506 non-null   uint8
 32  sunny      3506 non-null   uint8
dtypes: datetime64[ns](1), float64(5), int64(1), uint8(26)
memory usage: 280.9 KB

In [ ]:
import woodwork as ww
data.ww.init()
data.ww

            Physical Type Logical Type Semantic Tag(s)
Column
ds         datetime64[ns]     Datetime              []
target_id           int64      Integer     ['numeric']
y                 float64       Double     ['numeric']
reg_wind          float64       Double     ['numeric']
reg_r             float64       Double     ['numeric']
temp_max          float64       Double     ['numeric']
temp_min          float64       Double     ['numeric']
event2              int64      Integer     ['numeric']
event3              int64      Integer     ['numeric']
no event            int64      Integer     ['numeric']
cat_r_1             int64      Integer     ['numeric']
みどりの日               int64      Integer     ['numeric']
休日なし                int64      Integer     ['numeric']
体育の日                int64      Integer     ['numeric']
元日                  int64      Integer     ['numeric']
勤労感謝の日              int64      Integer     ['numeric']
国民の休日               int64      Integer     ['numeric']
天皇の即位の日             int64      Integer     ['numeric']
天皇誕生日               int64      Integer     ['numeric']
山の日                 int64      Integer     ['numeric']
建国記念の日              int64      Integer     ['numeric']
憲法記念日               int64      Integer     ['numeric']
成人の日                int64      Integer     ['numeric']
振替休日                int64      Integer     ['numeric']
敬老の日                int64      Integer     ['numeric']
文化の日                int64      Integer     ['numeric']
春分の日                int64      Integer     ['numeric']
昭和の日                int64      Integer     ['numeric']
海の日                 int64      Integer     ['numeric']
秋分の日                int64      Integer     ['numeric']
rain                int64      Integer     ['numeric']
snow                int64      Integer     ['numeric']
sunny               int64      Integer     ['numeric']

In [ ]:
#data = data.set_index('ds')

In [ ]:
X = data.drop(['y'],axis=1)
X

             ds  target_id  reg_wind      reg_r  ...  秋分の日  rain  snow  sunny
0    2015-01-01          0       4.4  17.856631  ...     0     0     0      0
1    2015-01-02          0       2.1  -2.435871  ...     0     0     0      1
2    2015-01-03          0       3.0  15.382444  ...     0     0     0      1
3    2015-01-04          0       1.3  11.864588  ...     0     0     0      0
4    2015-01-05          0       2.4 -14.973754  ...     0     0     0      1
...         ...        ...       ...        ...  ...   ...   ...   ...    ...
3501 2019-10-15          1       2.8   2.630001  ...     0     0     0      1
3502 2019-10-16          1       2.2  23.602167  ...     0     0     0      1
3503 2019-10-17          1       1.8  18.308426  ...     0     0     0      0
3504 2019-10-18          1       2.5   2.687561  ...     0     0     0      0
3505 2019-10-19          1       2.3   1.160098  ...     0     0     0      0

[3506 rows x 32 columns]

In [ ]:
data['target_id'].unique()

array([0, 1])

In [ ]:
a=data.groupby("target_id")
a

In [ ]:
y = data['y']
y

0        89.058108
1        88.638431
2        80.884749
3        89.288376
4        86.867064
           ...
3501    156.960567
3502    130.886110
3503    137.061111
3504    139.740341
3505    140.167169
Name: y, Length: 3506, dtype: float64

In [ ]:
data.shape

(3506, 33)

In [ ]:
import evalml
X_train, X_test, y_train, y_test = evalml.preprocessing.split_data(X, y, problem_type='time series multiclass')

In [ ]:
X_train.shape

(2804, 32)

In [ ]:
from evalml.automl import AutoMLSearch

model = AutoMLSearch(X_train, y_train, problem_type="time series regression",
                      max_batches=1,problem_configuration={"gap": 0, "max_delay": 200,
                                             "forecast_horizon": 200, "time_index": "ds"})
model.search()

Time series support in evalml is still in beta, which means we are still actively building its core features. Please be mindful of that when running search().
Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.770e+03, tolerance: 6.295e+00
Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.014e+04, tolerance: 1.588e+01
Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.329e+04, tolerance: 4.646e+01
stepwise model cannot be fit in parallel (n_jobs=1). Falling back to stepwise parameter search.
Maximum Likelihood optimization failed to converge. Check mle_retvals
Maximum Likelihood optimization failed to converge. Check mle_retvals
Maximum Likelihood optimization failed to converge. Check mle_retvals
Maximum Likelihood optimization failed to converge. Check mle_retvals
Maximum Likelihood optimization failed to converge. Check mle_retvals
stepwise model cannot be fit in parallel (n_jobs=1). Falling back to stepwise parameter search.
Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
Non-invertible starting MA parameters found. Using zeros as starting parameters.
Maximum Likelihood optimization failed to converge. Check mle_retvals
Maximum Likelihood optimization failed to converge. Check mle_retvals
Maximum Likelihood optimization failed to converge. Check mle_retvals
Maximum Likelihood optimization failed to converge. Check mle_retvals
Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
Non-invertible starting MA parameters found. Using zeros as starting parameters.
Maximum Likelihood optimization failed to converge. Check mle_retvals
Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
Non-invertible starting MA parameters found. Using zeros as starting parameters.
Maximum Likelihood optimization failed to converge. Check mle_retvals
Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
Non-invertible starting MA parameters found. Using zeros as starting parameters.
Maximum Likelihood optimization failed to converge. Check mle_retvals
Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
Non-invertible starting MA parameters found. Using zeros as starting parameters.
Maximum Likelihood optimization failed to converge. Check mle_retvals
Maximum Likelihood optimization failed to converge. Check mle_retvals
Maximum Likelihood optimization failed to converge. Check mle_retvals
Maximum Likelihood optimization failed to converge. Check mle_retvals
Maximum Likelihood optimization failed to converge. Check mle_retvals
stepwise model cannot be fit in parallel (n_jobs=1). Falling back to stepwise parameter search.
Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
Non-invertible starting MA parameters found. Using zeros as starting parameters.
Maximum Likelihood optimization failed to converge. Check mle_retvals
Maximum Likelihood optimization failed to converge. Check mle_retvals
Maximum Likelihood optimization failed to converge. Check mle_retvals
Maximum Likelihood optimization failed to converge. Check mle_retvals
Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
Maximum Likelihood optimization failed to converge. Check mle_retvals
Maximum Likelihood optimization failed to converge. Check mle_retvals
Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
Non-invertible starting MA parameters found. Using zeros as starting parameters.
Maximum Likelihood optimization failed to converge. Check mle_retvals
Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
Non-invertible starting MA parameters found. Using zeros as starting parameters.
Maximum Likelihood optimization failed to converge. Check mle_retvals
Maximum Likelihood optimization failed to converge. Check mle_retvals
Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
Non-invertible starting MA parameters found. Using zeros as starting parameters.
Maximum Likelihood optimization failed to converge. Check mle_retvals
Maximum Likelihood optimization failed to converge. Check mle_retvals
Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
Non-invertible starting MA parameters found. Using zeros as starting parameters.
Maximum Likelihood optimization failed to converge. Check mle_retvals
Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
Non-invertible starting MA parameters found. Using zeros as starting parameters.
Maximum Likelihood optimization failed to converge. Check mle_retvals

In [ ]:
model.rankings

   id  ...                                         parameters
0   0  ...  {'Time Series Featurizer': {'time_index': 'ds'...
1   9  ...  {'Imputer': {'categorical_impute_strategy': 'm...
2   8  ...  {'Imputer': {'categorical_impute_strategy': 'm...
3   7  ...  {'Imputer': {'categorical_impute_strategy': 'm...
4   4  ...  {'Imputer': {'categorical_impute_strategy': 'm...
5   6  ...  {'Imputer': {'categorical_impute_strategy': 'm...
6   3  ...  {'Imputer': {'categorical_impute_strategy': 'm...
7   5  ...  {'Imputer': {'categorical_impute_strategy': 'm...
8   2  ...  {'Imputer': {'categorical_impute_strategy': 'm...
9   1  ...  {'Imputer': {'categorical_impute_strategy': 'm...

[10 rows x 9 columns]

In [ ]:
model.best_pipeline

pipeline = TimeSeriesRegressionPipeline(component_graph={'Time Series Featurizer': ['Time Series Featurizer', 'X', 'y'], 'Time Series Baseline Estimator': ['Time Series Baseline Estimator', 'Time Series Featurizer.x', 'y']}, parameters={'Time Series Featurizer':{'time_index': 'ds', 'max_delay': 0, 'delay_target': True, 'delay_features': False, 'forecast_horizon': 200, 'conf_level': 0.05, 'gap': 0, 'rolling_window_size': 0.25}, 'Time Series Baseline Estimator':{'gap': 0, 'forecast_horizon': 200}, 'pipeline':{'time_index': 'ds', 'gap': 0, 'max_delay': 0, 'forecast_horizon': 200}}, custom_name='Time Series Baseline Regression Pipeline', random_seed=0)

In [ ]:
pl = model.best_pipeline

In [ ]:
pred = pl.predict_in_sample(X_test, y_test, objective=None, X_train=X_train, y_train=y_train)

In [ ]:
print(X_train.shape)
y_train.shape

(2804, 32)

(2804,)

In [ ]:
x = X_test.iloc[: pl.forecast_horizon].reset_index(drop=True)

In [ ]:
future_data = data.drop('y',axis=1)
future_data[:1000]

            ds  target_id  reg_wind      reg_r  ...  秋分の日  rain  snow  sunny
0   2015-01-01          0       4.4  17.856631  ...     0     0     0      0
1   2015-01-02          0       2.1  -2.435871  ...     0     0     0      1
2   2015-01-03          0       3.0  15.382444  ...     0     0     0      1
3   2015-01-04          0       1.3  11.864588  ...     0     0     0      0
4   2015-01-05          0       2.4 -14.973754  ...     0     0     0      1
..         ...        ...       ...        ...  ...   ...   ...   ...    ...
995 2017-09-22          0       2.3   8.982613  ...     0     0     0      0
996 2017-09-23          0       2.6   7.060940  ...     1     0     0      0
997 2017-09-24          0       2.1   7.067158  ...     0     0     0      0
998 2017-09-25          0       2.3   3.304602  ...     0     0     0      1
999 2017-09-26          0       2.5  11.086734  ...     0     0     0      1

[1000 rows x 32 columns]

In [ ]:
future_data.iloc[: pl.forecast_horizon].reset_index(drop=True)

            ds  target_id  reg_wind      reg_r  ...  秋分の日  rain  snow  sunny
0   2015-01-01          0       4.4  17.856631  ...     0     0     0      0
1   2015-01-02          0       2.1  -2.435871  ...     0     0     0      1
2   2015-01-03          0       3.0  15.382444  ...     0     0     0      1
3   2015-01-04          0       1.3  11.864588  ...     0     0     0      0
4   2015-01-05          0       2.4 -14.973754  ...     0     0     0      1
..         ...        ...       ...        ...  ...   ...   ...   ...    ...
195 2015-07-15          0       4.7   8.812665  ...     0     0     0      1
196 2015-07-16          0       4.8  12.261736  ...     0     0     0      0
197 2015-07-17          0       5.3   7.126523  ...     0     0     0      0
198 2015-07-18          0       5.5  11.342586  ...     0     0     0      0
199 2015-07-19          0       3.3   9.948772  ...     0     0     0      1

[200 rows x 32 columns]

In [ ]:
print(X_train.shape)
y_train.shape

(2804, 32)

(2804,)

In [ ]:
 future_pred = pl.predict(
        future_data.iloc[:1000].reset_index(drop=True),
        objective=None,
        X_train=X_train,
        y_train=y_train,
    )

In [ ]:
future_pred

2804    199.182761
2805    195.819116
2806    185.488315
2807    203.575448
2808    207.021209
           ...
3799     89.058108
3800     89.058108
3801     89.058108
3802     89.058108
3803     89.058108
Name: y, Length: 1000, dtype: float64